package com.example.lostify.ui.theme

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.example.lostify.data.ItemType
import com.example.lostify.data.LostItemEntity
import com.example.lostify.data.LostItemRepository
import com.example.lostify.data.LostifyDatabase
import kotlinx.coroutines.launch

class AddItemViewModel(
    application: Application
) : AndroidViewModel(application) {

    private val repository: LostItemRepository

    init {
        val database = LostifyDatabase.getDatabase(application)
        repository = LostItemRepository(database.lostItemDao())
    }

    fun addItem(
        type: ItemType,
        title: String,
        location: String,
        description: String,
        contactNumber: String,
        email: String,
        imageUri: String?
    ) {
        // Prevent empty submissions
        if (title.isBlank() || location.isBlank()) return

        val newItem = LostItemEntity(
            id = 0, // Auto-generated by Room
            type = type,
            title = title.trim(),
            location = location.trim(),
            description = description.trim(),
            timestamp = System.currentTimeMillis(),
            date = System.currentTimeMillis(),
            imageRes = null,
            contactNumber = contactNumber.trim(),
            email = email.trim(),
            imageUri = imageUri
        )

        viewModelScope.launch {
            repository.insertItem(newItem)
        }
    }
}
